ARG ARCH

#------------------------------------------------------------------------------------
#--------------------------build-----------------------------------------------------
#------------------------------------------------------------------------------------
# http://releases.ubuntu.com/focal/
FROM ${ARCH}ossrs/srs:ubuntu20-base4 as build4
FROM ${ARCH}ossrs/srs:ubuntu20-base50 as build50
FROM ${ARCH}ossrs/srs:ubuntu20-base51 as build51

#------------------------------------------------------------------------------------
#--------------------------dist------------------------------------------------------
#------------------------------------------------------------------------------------
# http://releases.ubuntu.com/focal/
FROM ${ARCH}ubuntu:focal as dist

ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG TARGETARCH
ARG JOBS=2
RUN echo "BUILDPLATFORM: $BUILDPLATFORM, TARGETPLATFORM: $TARGETPLATFORM, TARGETARCH: $TARGETARCH JOBS: $JOBS"

WORKDIR /tmp/srs

# See https://fonts.google.com/specimen/Roboto
# See https://fonts.google.com/noto/specimen/Noto+Sans+SC
ADD Roboto-Regular.ttf NotoSansSC-Regular.ttf /usr/local/share/fonts/

# Copy all FFmpeg versions and cmake and other tools in /usr/local.
COPY --from=build51 /usr/local /usr/local
COPY --from=build4 /usr/local/bin/ffmpeg4 /usr/local/bin/ffprobe4 /usr/local/bin/
COPY --from=build50 /usr/local/bin/ffmpeg5 /usr/local/bin/ffprobe5 /usr/local/bin/

# Note that for armv7, the ffmpeg5-hevc-over-rtmp is actually ffmpeg5.
RUN rm -f /usr/local/bin/ffmpeg && ln -sf /usr/local/bin/ffmpeg5-hevc-over-rtmp /usr/local/bin/ffmpeg && \
    rm -f /usr/local/bin/ffprobe && ln -sf /usr/local/bin/ffprobe5-hevc-over-rtmp /usr/local/bin/ffprobe && \
    echo "The size of binary:" && du -sh /usr/local/* && \
    echo "The usage of disk:" && df -h \

# Note that the PATH has /usr/local/bin by default in ubuntu:focal.
#ENV PATH=$PATH:/usr/local/bin

