ARG ARCH

#------------------------------------------------------------------------------------
#--------------------------build-----------------------------------------------------
#------------------------------------------------------------------------------------
# http://releases.ubuntu.com/focal/
FROM ${ARCH}ossrs/srs:ubuntu20-base50 AS build50
FROM ${ARCH}ossrs/srs:ubuntu20-base51 AS build51
FROM ${ARCH}ossrs/srs:ubuntu20-base52 AS build52
FROM ${ARCH}ossrs/srs:ubuntu20-base53 AS build53

#------------------------------------------------------------------------------------
#--------------------------dist------------------------------------------------------
#------------------------------------------------------------------------------------
# http://releases.ubuntu.com/focal/
FROM ${ARCH}ubuntu:focal AS dist

ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG TARGETARCH
ARG JOBS=2
RUN echo "BUILDPLATFORM: $BUILDPLATFORM, TARGETPLATFORM: $TARGETPLATFORM, TARGETARCH: $TARGETARCH JOBS: $JOBS"

WORKDIR /tmp/srs

# See https://fonts.google.com/specimen/Roboto
# See https://fonts.google.com/noto/specimen/Noto+Sans+SC
ADD Roboto-Regular.ttf NotoSansSC-Regular.ttf /usr/local/share/fonts/

# Copy all FFmpeg versions and cmake and other tools in /usr/local.
# Use the FFmpeg 8 build as the base so its libraries and runtime files are available.
COPY --from=build53 /usr/local /usr/local
COPY --from=build51 /usr/local/bin/ffmpeg5-hevc-over-rtmp /usr/local/bin/ffprobe5-hevc-over-rtmp /usr/local/bin/
COPY --from=build50 /usr/local/bin/ffmpeg5 /usr/local/bin/ffprobe5 /usr/local/bin/
COPY --from=build52 /usr/local/bin/ffmpeg7 /usr/local/bin/ffprobe7 /usr/local/bin/

# FFmpeg 8 supports HEVC over Enhanced RTMP/FLV without the legacy FFmpeg 5 patch.
RUN rm -f /usr/local/bin/ffmpeg && ln -sf /usr/local/bin/ffmpeg8 /usr/local/bin/ffmpeg && \
    rm -f /usr/local/bin/ffprobe && ln -sf /usr/local/bin/ffprobe8 /usr/local/bin/ffprobe && \
    /usr/local/bin/ffmpeg -version | head -n 1 | grep -q 'ffmpeg version 8.1.2' && \
    /usr/local/bin/ffprobe -version | head -n 1 | grep -q 'ffprobe version 8.1.2' && \
    echo "The size of binary:" && du -sh /usr/local/* && \
    echo "The usage of disk:" && df -h \

# Note that the PATH has /usr/local/bin by default in ubuntu:focal.
#ENV PATH=$PATH:/usr/local/bin
